# Generated by Django 6.0.7 on 2026-07-15 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Answer",
            new_name="Choice",
        ),
    ]
